name = "Joshua Grubbs, Ph.D."
license = 
licenselink = 
description = 
homepage =
demosite = 
tags = ["widgets",
        "resume",
        "portfolio",
        "responsive",
        "clean",
        "personal",
        "company",
        "blog",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "documentation",
        "landing page",
        "projects",
        "single page",
        "contact form",
        "mobile",
        "gallery",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "product",
        "slide"
        ]
features = ["widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "Joshua B. Grubbs, Ph.D."
  homepage = "https://joshuagrubbsphd.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
